# Generated by Django 4.1.1 on 2023-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_numbers_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='numbers',
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
