# Generated by Django 4.1.1 on 2023-06-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_remove_person_numbers_delete_numbers_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default=0, max_length=200, verbose_name='نام در url'),
            preserve_default=False,
        ),
    ]
