services:
  django-shop:
    container_name: django-shop
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app