# Generated by Django 4.1.1 on 2023-07-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'جزئیات سبد خرید', 'verbose_name_plural': 'لیست جزئیات سبد های خرید'},
        ),
    ]
