# Generated by Django 4.1.1 on 2023-04-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
