# Generated by Django 4.1.1 on 2023-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_sitebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزئیات محصولات')], max_length=200, verbose_name='جایگاه نمایش'),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='آدرس بنر'),
        ),
    ]
