# Generated by Django 4.1.1 on 2023-05-09 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 5, 10), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
