# Generated by Django 4.1.1 on 2023-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=True, verbose_name='کاربر ویژه'),
        ),
    ]
