# Generated by Django 4.1.1 on 2023-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='کاربر ویژه'),
        ),
    ]
